/// @description set_list_words()
/// @param ls

var ls = argument0;

ds_list_add(ls, "PALEONTOLOGYST", "CRETACEOUS", "JURASSIC", "TRIASSIC");
ds_list_add(ls, "TYRANNOSAURUS", "STEGOSAURUS", "TRICERATOPS", "VELOCIRAPTOR");
ds_list_add(ls, "SPINOSAURUS", "ALLOSAURUS", "ARCHAEOPTERYX", "MEGALOSAURUS");
ds_list_add(ls, "DIPLODOCUS", "ANKYLOSAURUS", "BRACHIOSAURUS", "IGUANODON");
ds_list_add(ls, "PARASAUROLOPHUS", "HADROSAURUS", "COMPSOGNATHUS", "PACHYCEPHALOSAURUS");